name: Automatic merge from master to next-version
on:
  push:
    branches:
      - master
jobs:
  automerge_master_to_next_version:
    name: Merge master into next-version after a PR is merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout next-version
        uses: actions/checkout@v3
        with:
          ref: next-version
          token: ${{ secrets.TI_GITHUB_ACTIONS_TOKEN }}
      - name: Auto Merge
        id: automerge
        uses: devmasx/merge-branch@v1.4.0
        with:
          type: now
          from_branch: master
          target_branch: next-version
          github_token: ${{ secrets.TI_GITHUB_ACTIONS_TOKEN }}
          label_name: AutoMerge
        env:
          INPUT_MESSAGE: Auto merge master into next-version
